name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Lint
        run: pylint src/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t backend-app:latest .

  ecr-login:
    name: ECR Login
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}

  push:
    name: Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: ecr-login
    steps:
      - name: Push Docker Image
        run: |
          aws ecr create-repository --repository-name backend-app || true
          docker tag backend-app:latest ${{ secrets.ECR_REGISTRY }}/backend-app:latest
          docker push ${{ secrets.ECR_REGISTRY }}/backend-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.23.0'

      - name: Configure kubectl
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy Application
        run: |
          kubectl set image deployment/backend-app backend-app=${{ secrets.ECR_REGISTRY }}/backend-app:latest
          kubectl rollout status deployment/backend-app
