jobs:
  Linting:
    runs-on: ubuntu-latest
    environment: Development Environment

    steps:
      - name: Check the Repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: starter/backend/package-lock.json

      - name: Install Dependencies
        working-directory: starter/backend
        run: npm ci

      - name: Run Lint
        working-directory: starter/backend
        run: npm run lint

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Check the Repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: starter/backend/package-lock.json

      - name: Install Dependencies
        working-directory: starter/backend
        run: npm ci

      - name: Run Tests
        working-directory: starter/backend
        run: npm run test

  Build:
    needs: [Linting, Test]
    runs-on: ubuntu-latest

    steps:
      - name: Check the Repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: starter/backend/package-lock.json

      - name: Build and Run Docker Image
        working-directory: starter/backend
        run: |
          docker build --tag=backend-app:latest .
          docker run --name backend-app -d backend-app
