Push_to_ECR:
  needs: [Build]
  runs-on: ubuntu-latest
  steps:
    - name: Check the Repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials for ECR
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # Replacing the Login step with manual authentication
    - name: Authenticate to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 427848260902.dkr.ecr.us-east-1.amazonaws.com

    - name: Push Docker Image to Amazon ECR
      run: |
        docker tag frontend-app:latest 427848260902.dkr.ecr.us-east-1.amazonaws.com/frontend-app:latest
        docker push 427848260902.dkr.ecr.us-east-1.amazonaws.com/frontend-app:latest
